Adding virtual shader

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -1,5 +1,4 @@
 name: 3 | Android
-
 on: 
   workflow_call:
     inputs:
@@ -11,9 +10,7 @@ on:
       version:
         description: 'Addon version'
         required: true
-        default: "6.0"
-
-run-name: Android build - ${{ inputs.version }}
+        default: '7.0'
 
 env:
   ANDROID_SDK_ROOT: '/opt/android-sdk'
@@ -27,8 +24,9 @@ env:
   CMAKE_VERSION: '3.22.1'
   JAVA_VERSION: '17'
 
+run-name: Android build - ${{ inputs.version }}
 jobs:
-  build:
+  build_android_arm64:
     runs-on: ubuntu-latest
     container:
       image: archlinux:latest
@@ -88,15 +86,11 @@ jobs:
 
       - name: Compiling FFmpeg arm64
         run: python -c 'import build; build.compile_ffmpeg_android("arm64")'
-      #- name: Compiling FFmpeg armv7a
-      #  run: python -c 'import build; build.compile_ffmpeg_android("armv7a")'
 
       - name: Build Android debug + release
         run: |
           scons -j4 target=template_debug platform=android arch=arm64
           scons -j4 target=template_release platform=android arch=arm64
-      #    scons -j4 target=template_debug platform=android arch=armv7a
-      #    scons -j4 target=template_release platform=android arch=armv7a
         env:
           ANDROID_NDK: ${{ env.ANDROID_NDK }}
           ANDROID_SDK: ${{ env.ANDROID_SDK }}
@@ -105,7 +99,85 @@ jobs:
       - name: Uploading Android bin
         uses: actions/upload-artifact@v4
         with:
-          name: bin_android
+          name: bin_android_armv8
           path: test_room/addons/gde_gozen/bin
-          retention-days: 1
+          retention-days: 5
+
+
+  build_android_arm32:
+    runs-on: ubuntu-latest
+    container:
+      image: archlinux:latest
+    steps:
+      - name: Installing dependencies
+        run: pacman -Syu --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar ffmpeg gradle libtool nasm cmake jdk${JAVA_VERSION}-openjdk
+
+      - name: Set ANDROID_HOME and ANDROID_NDK_ROOT environment variables
+        run: |
+          echo "ANDROID_HOME=${ANDROID_SDK_ROOT}" >> $GITHUB_ENV
+          echo "ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk/${NDK_VERSION}" >> $GITHUB_ENV
+          echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH
+          echo "${ANDROID_SDK_ROOT}/platform-tools" >> $GITHUB_PATH
+          echo "${ANDROID_SDK_ROOT}/ndk/${NDK_VERSION}" >> $GITHUB_PATH
+
+      # Android stuff
+      - name: Setup Android SDK on Arch
+        run: |
+          set -e # Exit if a command exits with a non-zero status.
+          CMDLINE_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
+          echo "Downloading Android Command-line tools..."
+          wget -q "${CMDLINE_TOOLS_URL}" -O cmdline-tools.zip
+
+          echo "Installing to ${ANDROID_SDK_ROOT}/cmdline-tools/latest..."
+          mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools/latest"
+          unzip -q cmdline-tools.zip -d "${ANDROID_SDK_ROOT}/cmdline-tools/temp"
+
+          mv "${ANDROID_SDK_ROOT}/cmdline-tools/temp/cmdline-tools/"* "${ANDROID_SDK_ROOT}/cmdline-tools/latest/"
+          rm -rf "${ANDROID_SDK_ROOT}/cmdline-tools/temp" cmdline-tools.zip
+
+          echo "Installed cmdline-tools:"
+          ls -la "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin"
+
+      - name: Accept SDK Licenses and Install SDK Components (including NDK)
+        run: |
+          set -e
+          echo "Accepting licenses..."
+
+          # Create dummy file expected by sdkmanager for license stuff.
+          mkdir -p ${ANDROID_SDK_ROOT}/licenses/
+          yes | sdkmanager --licenses || echo "License acceptance might have had non-zero exit code but continuing..."
+
+          echo "Installing SDK components..."
+          sdkmanager --install "ndk;${NDK_VERSION}" \
+                               "platform-tools" \
+                               "platforms;android-${ANDROID_PLATFORM_VERSION}" \
+                               "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" \
+                               --sdk_root=${ANDROID_SDK_ROOT}
+
+          echo "Verifying NDK installation..."
+          ls -la "${ANDROID_NDK_ROOT}" # Check if NDK directory exists.
+          
+      - name: Checkout submodules
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Compiling FFmpeg armv7a
+        run: python -c 'import build; build.compile_ffmpeg_android("armv7a")'
+
+      - name: Build Android debug + release
+        run: |
+          scons -j4 target=template_debug platform=android arch=armv7a
+          scons -j4 target=template_release platform=android arch=armv7a
+        env:
+          ANDROID_NDK: ${{ env.ANDROID_NDK }}
+          ANDROID_SDK: ${{ env.ANDROID_SDK }}
+          ANDROID_HOME: ${{ env.ANDROID_HOME }}
+
+      - name: Uploading Android bin
+        uses: actions/upload-artifact@v4
+        with:
+          name: bin_android_armv7a
+          path: test_room/addons/gde_gozen/bin
+          retention-days: 5
 
